### ISSUE TITLE
Setup Not working

### ISSUE THREAD

**Issue by MatthiasRathbun** [rsmith-nl/beammech#2] opened 2018-03-26 20:23 UTC
Setup Code will not wor. Gives unicode error.  UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 3651: character maps to <undefined>

**Comment by rsmith-nl** [comment] 2018-04-02 08:01
Which version of Python are you using?

**Comment by MatthiasRathbun** [comment] 2018-04-04 19:59
I am using python 3. It may be a pip error, but the same error occurred with another module too. It may be a local error.

**Comment by rsmith-nl** [comment] 2018-06-10 14:05
Running `python3 setup.py install` works fine here. So I'm closing this issue since I cannot reproduce it.

**Closed as completed by rsmith-nl** 2018-06-10 14:05 UTC
